package org.apache.seatunnel.web.core.client.service;

import org.apache.seatunnel.web.core.client.port.SeaTunnelClientRuntimeGateway;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

/**
 * Domain service for accessing SeaTunnel client runtime capabilities.
 *
 * <p>This service provides a stable runtime-facing API for upper layers and delegates
 * the actual engine communication to {@link SeaTunnelClientRuntimeGateway}.</p>
 *
 * <p>The service itself does not depend on any concrete communication protocol.
 * The runtime gateway implementation may use SeaTunnel REST API, SDK, or other
 * mechanisms to access the engine.</p>
 */
@Component
public class SeaTunnelClientRuntimeService {

    private final SeaTunnelClientRuntimeGateway runtimeGateway;

    public SeaTunnelClientRuntimeService(SeaTunnelClientRuntimeGateway runtimeGateway) {
        this.runtimeGateway = runtimeGateway;
    }

    /**
     * Queries raw runtime metrics of a SeaTunnel client.
     *
     * @param clientId SeaTunnel client id
     * @return raw metrics returned by the runtime gateway
     */
    public List<Map<String, Object>> metrics(Long clientId) {
        return runtimeGateway.metrics(clientId);
    }

    /**
     * Queries job logs from the SeaTunnel engine.
     *
     * <p>The default log response format is JSON because the frontend usually needs
     * structured log content for rendering and filtering.</p>
     *
     * @param clientId SeaTunnel client id
     * @param engineJobId job id generated by the SeaTunnel engine
     * @return job log content in JSON format
     */
    public String logs(Long clientId, String engineJobId) {
        if (clientId == null) {
            throw new IllegalArgumentException("clientId cannot be empty");
        }

        if (engineJobId == null || engineJobId.trim().isEmpty()) {
            throw new IllegalArgumentException("engineJobId cannot be empty");
        }

        return runtimeGateway.jobLogs(clientId, engineJobId, "json");
    }

    /**
     * Queries checkpoint overview of a SeaTunnel job.
     *
     * @param clientId SeaTunnel client id
     * @param jobId SeaTunnel engine job id
     * @return checkpoint overview information
     */
    public Map<String, Object> checkpointOverview(Long clientId, Long jobId) {
        return runtimeGateway.checkpointOverview(clientId, jobId);
    }

    /**
     * Queries checkpoint history of a SeaTunnel job.
     *
     * @param clientId SeaTunnel client id
     * @param jobId SeaTunnel engine job id
     * @param pipelineId optional pipeline id
     * @param limit max history size
     * @param status optional checkpoint status filter
     * @return checkpoint history list
     */
    public List<Map<String, Object>> checkpointHistory(
            Long clientId,
            Long jobId,
            Long pipelineId,
            Integer limit,
            String status
    ) {
        return runtimeGateway.checkpointHistory(
                clientId,
                jobId,
                pipelineId,
                limit,
                status
        );
    }
}
