import type { PrototypePageMeta } from './types';

const requirements = {
  forms: ['F-01.01', 'F-01.02', 'F-01.03', 'F-01.04', 'F-01.05', 'F-01.06', 'F-01.07'],
  reports: ['F-05.01', 'F-05.02', 'F-05.03'],
  datasource: ['F-04.02'],
  client: ['P-03'],
  discovery: ['F-02.03', 'F-04.01', 'F-13.01'],
  batch: ['F-02.01', 'F-02.02', 'F-03.01', 'F-03.03', 'F-03.04', 'F-03.05', 'F-03.07', 'F-06.01', 'P-01', 'P-03', 'P-04', 'P-06'],
  stream: ['F-02.01', 'F-03.01', 'F-03.03', 'F-03.04', 'F-03.07', 'F-06.01', 'P-01', 'P-03', 'P-04', 'P-06'],
  cloudEdge: ['F-08.01', 'F-08.02', 'F-08.03'],
  edge: ['F-10.01', 'F-10.02', 'F-10.03', 'F-14.01', 'F-14.02', 'F-14.03'],
  links: ['F-12.01', 'F-12.02', 'F-12.03'],
  topology: ['F-13.02', 'F-13.03'],
  bi: ['F-09.01', 'F-09.02'],
  metrics: ['F-03.02', 'F-09.02'],
  alarm: ['F-03.06', 'P-05'],
  diagnostics: ['F-11.01', 'F-11.02', 'F-11.03', 'F-12.03'],
  lake: ['F-06.01', 'P-02'],
  lifecycle: ['F-15.01', 'F-15.02', 'F-15.03'],
  logical: ['F-06.02'],
  knowledge: ['F-03.03', 'F-07.02'],
  openApi: ['F-07.01', 'F-07.02'],
};

export const prototypePageRegistry: PrototypePageMeta[] = [
  {
    id: 'reporting-forms',
    firstMenu: '数据采报',
    secondMenu: '数据采报管理',
    route: '/reporting/forms',
    technicalModules: ['MOD-001'],
    implementationStatus: 'INTEGRATE',
    requirementIds: requirements.forms,
    source: '拟集成 TDuck 社区版 API / WebHook',
    description: '模板、发布、模拟填报、提交和批次状态闭环。',
    prototypeKind: 'forms',
  },
  {
    id: 'reporting-reports',
    firstMenu: '数据采报',
    secondMenu: '采集报告管理',
    route: '/reporting/reports',
    technicalModules: ['MOD-001'],
    implementationStatus: 'BUILD',
    requirementIds: requirements.reports,
    source: '新增轻量报告页，复用 TDuck 答卷与统计数据',
    description: '报告生成、预览、导出和分发记录。',
    prototypeKind: 'reports',
  },
  {
    id: 'data-source',
    firstMenu: '引接资源',
    secondMenu: '数据源管理',
    route: '/data-source',
    technicalModules: ['MOD-002'],
    implementationStatus: 'REUSE',
    requirementIds: requirements.datasource,
    source: 'src/pages/data-source',
    description: '复用数据源注册、编辑、连接测试和驱动管理。',
    prototypeKind: 'reused',
  },
  {
    id: 'client',
    firstMenu: '引接资源',
    secondMenu: '引擎管理',
    route: '/client',
    technicalModules: ['MOD-004', 'MOD-005'],
    implementationStatus: 'ADAPT',
    requirementIds: requirements.client,
    source: 'src/pages/client',
    description: '复用 Client 页面并统一为引擎节点语义。',
    prototypeKind: 'reused',
  },
  {
    id: 'data-discovery',
    firstMenu: '引接资源',
    secondMenu: '数据探查',
    route: '/resources/data-discovery',
    technicalModules: ['MOD-002'],
    implementationStatus: 'INTEGRATE',
    requirementIds: requirements.discovery,
    source: '拟集成 OpenMetadata API',
    description: '资产树、字段、画像与质量上下文。',
    prototypeKind: 'discovery',
  },
  {
    id: 'batch-link-up',
    firstMenu: '数据引接',
    secondMenu: '离线引接任务管理',
    route: '/sync/batch-link-up',
    technicalModules: ['MOD-003', 'MOD-004'],
    implementationStatus: 'REUSE',
    requirementIds: requirements.batch,
    source: 'src/pages/batch-link-up',
    description: '复用离线任务、调度、执行和历史页面。',
    prototypeKind: 'reused',
  },
  {
    id: 'stream-link-up',
    firstMenu: '数据引接',
    secondMenu: '实时引接任务管理',
    route: '/sync/stream-link-up',
    technicalModules: ['MOD-003', 'MOD-004'],
    implementationStatus: 'ADAPT',
    requirementIds: requirements.stream,
    source: 'src/pages/stream-link-up',
    description: '复用实时任务主干并补齐检查点交互。',
    prototypeKind: 'reused',
  },
  {
    id: 'cloud-edge',
    firstMenu: '数据引接',
    secondMenu: '云边协同任务管理',
    route: '/sync/cloud-edge-tasks',
    technicalModules: ['MOD-008'],
    implementationStatus: 'LIMITED',
    requirementIds: requirements.cloudEdge,
    source: '新增 PoC 页面与受控模拟',
    description: '任务下发、断网暂存、恢复续传与状态回传。',
    prototypeKind: 'cloud-edge',
  },
  {
    id: 'edge-access',
    firstMenu: '数据引接',
    secondMenu: '边缘接入任务管理',
    route: '/sync/edge-access-tasks',
    technicalModules: ['MOD-007', 'MOD-008'],
    implementationStatus: 'LIMITED',
    requirementIds: requirements.edge,
    source: '新增协议接入 PoC 页面',
    description: '协议选择、连通测试、边缘代理和启停。',
    prototypeKind: 'edge-access',
  },
  {
    id: 'links',
    firstMenu: '数据引接',
    secondMenu: '引接链路管理',
    route: '/sync/links',
    technicalModules: ['MOD-006'],
    implementationStatus: 'BUILD',
    requirementIds: requirements.links,
    source: '复用批流任务状态，新增统一链路视图',
    description: '来源、目标、任务、路由和健康状态。',
    prototypeKind: 'links',
  },
  {
    id: 'topology',
    firstMenu: '数据引接',
    secondMenu: '数据拓扑管理',
    route: '/sync/topology',
    technicalModules: ['MOD-006'],
    implementationStatus: 'INTEGRATE',
    requirementIds: requirements.topology,
    source: '拟集成 OpenMetadata 血缘',
    description: 'DAG 缩放、节点高亮和影响分析。',
    prototypeKind: 'topology',
  },
  {
    id: 'bi',
    firstMenu: '运行运维',
    secondMenu: '引接态势',
    route: '/bi',
    technicalModules: ['MOD-005'],
    implementationStatus: 'ADAPT',
    requirementIds: requirements.bi,
    source: 'src/pages/bi',
    description: '改造现有数据洞察页面的数据口径。',
    prototypeKind: 'reused',
  },
  {
    id: 'metrics',
    firstMenu: '运行运维',
    secondMenu: '运行监控',
    route: '/metrics',
    technicalModules: ['MOD-005'],
    implementationStatus: 'REUSE',
    requirementIds: requirements.metrics,
    source: 'src/pages/metrics',
    description: '复用同步记录量、数据量和处理速率监控。',
    prototypeKind: 'reused',
  },
  {
    id: 'alarm',
    firstMenu: '运行运维',
    secondMenu: '告警管理',
    route: '/alarm',
    technicalModules: ['MOD-005'],
    implementationStatus: 'REUSE',
    requirementIds: requirements.alarm,
    source: 'src/pages/alarm',
    description: '复用告警通道、规则和记录页面。',
    prototypeKind: 'reused',
  },
  {
    id: 'diagnostics',
    firstMenu: '运行运维',
    secondMenu: '故障辅助',
    route: '/operations/diagnostics',
    technicalModules: ['MOD-005'],
    implementationStatus: 'LIMITED',
    requirementIds: requirements.diagnostics,
    source: '复用日志与指标，新增固定诊断规则',
    description: '故障时间线、证据、建议和安全重试。',
    prototypeKind: 'diagnostics',
  },
  {
    id: 'lake-resources',
    firstMenu: '入湖管理',
    secondMenu: '入湖资源管理',
    route: '/lake/resources',
    technicalModules: ['MOD-003', 'MOD-009'],
    implementationStatus: 'BUILD',
    requirementIds: requirements.lake,
    source: '复用数据源连接，新增湖目标视图',
    description: '湖目标、格式、分区、测试和任务引用。',
    prototypeKind: 'lake-resources',
  },
  {
    id: 'lifecycle',
    firstMenu: '入湖管理',
    secondMenu: '数据生命周期管理',
    route: '/lake/lifecycle',
    technicalModules: ['MOD-009'],
    implementationStatus: 'BUILD',
    requirementIds: requirements.lifecycle,
    source: '新增固定生命周期策略页面',
    description: '有效期、TTL、归档、清理和执行记录。',
    prototypeKind: 'lifecycle',
  },
  {
    id: 'logical-access',
    firstMenu: '入湖管理',
    secondMenu: '逻辑入湖管理',
    route: '/lake/logical-access',
    technicalModules: ['MOD-009'],
    implementationStatus: 'LIMITED',
    requirementIds: requirements.logical,
    source: '新增受控逻辑映射与查询预览',
    description: '跨源映射、联邦查询入口和服务引用。',
    prototypeKind: 'logical-access',
  },
  {
    id: 'knowledge',
    firstMenu: '系统管理',
    secondMenu: '参数与知识',
    route: '/knowledge-management',
    technicalModules: ['MOD-004', 'MOD-007'],
    implementationStatus: 'REUSE',
    requirementIds: requirements.knowledge,
    source: 'src/pages/knowledge-management',
    description: '复用变量、时间参数和连接器知识。',
    prototypeKind: 'reused',
  },
  {
    id: 'open-api',
    firstMenu: '系统管理',
    secondMenu: '开放接口',
    route: '/open-api',
    technicalModules: ['MOD-007'],
    implementationStatus: 'REUSE',
    requirementIds: requirements.openApi,
    source: 'src/pages/open-api',
    description: '复用 OpenAPI 文档和调用说明。',
    prototypeKind: 'reused',
  },
];

export const findPageMeta = (pathname: string) =>
  prototypePageRegistry.find(
    ({ route }) => pathname === route || pathname.startsWith(`${route}/`),
  );

export const implementationLabels = {
  REUSE: '复用',
  ADAPT: '改造',
  INTEGRATE: '集成',
  BUILD: '新增',
  LIMITED: '有限实现',
} as const;

export const implementationColors = {
  REUSE: '#16a34a',
  ADAPT: '#2563eb',
  INTEGRATE: '#9333ea',
  BUILD: '#ea580c',
  LIMITED: '#ca8a04',
} as const;
