package org.apache.seatunnel.web.core.client.port;

import java.util.List;
import java.util.Map;

/**
 * Gateway interface for accessing SeaTunnel client runtime capabilities.
 *
 * <p>This port belongs to the core client module and only defines runtime operations
 * required by the upper application layer. The actual implementation can be based on
 * SeaTunnel REST API, SDK, or other communication mechanisms.</p>
 */
public interface SeaTunnelClientRuntimeGateway {

    /**
     * Queries runtime metrics of the specified SeaTunnel client.
     *
     * @param clientId SeaTunnel client id
     * @return raw runtime metrics returned by the engine
     */
    List<Map<String, Object>> metrics(Long clientId);

    /**
     * Queries job logs from the SeaTunnel engine.
     *
     * @param clientId SeaTunnel client id
     * @param engineJobId job id generated by the SeaTunnel engine
     * @param format log response format, such as json or text
     * @return engine job log content
     */
    String jobLogs(Long clientId, String engineJobId, String format);

    /**
     * Queries checkpoint overview of a SeaTunnel job.
     *
     * @param clientId SeaTunnel client id
     * @param jobId SeaTunnel engine job id
     * @return checkpoint overview information
     */
    Map<String, Object> checkpointOverview(Long clientId, Long jobId);

    /**
     * Queries checkpoint history of a SeaTunnel job.
     *
     * @param clientId SeaTunnel client id
     * @param jobId SeaTunnel engine job id
     * @param pipelineId optional pipeline id
     * @param limit max history size
     * @param status optional checkpoint status filter
     * @return checkpoint history list
     */
    List<Map<String, Object>> checkpointHistory(
            Long clientId,
            Long jobId,
            Long pipelineId,
            Integer limit,
            String status
    );
}
