-- v1.4 dual-mode lake control plane.  Historical V1.0.15-V1.0.20 tables are immutable.
-- IDs are generated by BaseEntity.initInsert(); no database foreign keys are used so
-- external-resource retries and historical generations remain auditable.

CREATE TABLE `t_seatunnel_web_lake_source_object_ref`
(
    `id`                    bigint       NOT NULL COMMENT '主键',
    `source_data_source_id` bigint       NOT NULL COMMENT '来源数据源 ID',
    `om_entity_id`          varchar(128) NOT NULL COMMENT 'OpenMetadata Entity UUID',
    `om_fqn`                varchar(512)          DEFAULT NULL COMMENT '当前 FQN',
    `object_type`           varchar(32)  NOT NULL DEFAULT 'TABLE' COMMENT 'TABLE',
    `source_schema_hash`    char(64)              DEFAULT NULL COMMENT 'Source Snapshot SHA-256',
    `source_snapshot_json`  longtext              COMMENT '脱敏 Source Snapshot',
    `resource_status`       varchar(32)  NOT NULL DEFAULT 'READY',
    `lock_version`          int          NOT NULL DEFAULT 1,
    `generation`            int          NOT NULL DEFAULT 1,
    `operation_token`       varchar(128)          DEFAULT NULL,
    `error_code`            varchar(128)          DEFAULT NULL,
    `error_message`         varchar(4096)         DEFAULT NULL,
    `last_reconcile_at`     datetime              DEFAULT NULL,
    `create_user_id`        int                   DEFAULT NULL,
    `update_user_id`        int                   DEFAULT NULL,
    `deleted`               tinyint(1)   NOT NULL DEFAULT 0,
    `create_time`            datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`            datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_lake_source_object_om_entity` (`om_entity_id`),
    KEY `idx_lake_source_object_datasource` (`source_data_source_id`, `resource_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='双模入湖 OpenMetadata 对象引用';

CREATE TABLE `t_seatunnel_web_lake_ods_database_binding`
(
    `id`                    bigint       NOT NULL COMMENT '主键',
    `lake_data_source_id`   bigint       NOT NULL COMMENT 'Doris 湖数据源 ID',
    `source_data_source_id` bigint       NOT NULL COMMENT '来源数据源 ID',
    `unit_code`             varchar(128) NOT NULL COMMENT '单位编码',
    `system_code`           varchar(128) NOT NULL COMMENT '业务系统编码',
    `database_name`         varchar(64)  NOT NULL COMMENT 'Doris Internal Database',
    `resource_status`       varchar(32)  NOT NULL DEFAULT 'PENDING_CREATE',
    `lock_version`          int          NOT NULL DEFAULT 1,
    `generation`            int          NOT NULL DEFAULT 1,
    `operation_token`       varchar(128)          DEFAULT NULL,
    `error_code`            varchar(128)          DEFAULT NULL,
    `error_message`         varchar(4096)         DEFAULT NULL,
    `last_reconcile_at`     datetime              DEFAULT NULL,
    `create_user_id`        int                   DEFAULT NULL,
    `update_user_id`        int                   DEFAULT NULL,
    `deleted`               tinyint(1)   NOT NULL DEFAULT 0,
    `create_time`            datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`            datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_lake_ods_database_source` (`source_data_source_id`),
    UNIQUE KEY `uk_lake_ods_database_target` (`lake_data_source_id`, `database_name`),
    KEY `idx_lake_ods_database_status` (`resource_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='双模入湖 ODS Database Binding';

CREATE TABLE `t_seatunnel_web_lake_ods_table_mapping`
(
    `id`                         bigint       NOT NULL COMMENT '主键',
    `source_object_ref_id`       bigint       NOT NULL COMMENT 'Source Object Ref ID',
    `ods_database_binding_id`    bigint       NOT NULL COMMENT 'ODS Database Binding ID',
    `lake_data_source_id`        bigint       NOT NULL COMMENT 'Doris 湖数据源 ID',
    `database_name`              varchar(64)  NOT NULL COMMENT 'Doris Internal Database',
    `target_table_name`          varchar(128) NOT NULL COMMENT 'Doris Internal Table',
    `management_level`           varchar(32)  NOT NULL COMMENT 'MANAGED/AUTO_CREATED/UNMANAGED',
    `table_model`                varchar(32)           DEFAULT NULL COMMENT 'DUPLICATE/UNIQUE',
    `source_schema_hash`         char(64)              DEFAULT NULL,
    `target_contract_hash`       char(64)              DEFAULT NULL,
    `source_snapshot_json`       longtext,
    `target_contract_json`       longtext,
    `field_mappings_json`        longtext,
    `source_consistency_status`  varchar(32)           DEFAULT NULL,
    `target_consistency_status`  varchar(32)           DEFAULT NULL,
    `task_consistency_status`    varchar(32)           DEFAULT NULL,
    `actual_table_exists`        tinyint(1)             DEFAULT NULL,
    `resource_status`            varchar(32)  NOT NULL DEFAULT 'PENDING_CREATE',
    `lock_version`               int          NOT NULL DEFAULT 1,
    `generation`                 int          NOT NULL DEFAULT 1,
    `operation_token`            varchar(128)          DEFAULT NULL,
    `error_code`                 varchar(128)          DEFAULT NULL,
    `error_message`              varchar(4096)         DEFAULT NULL,
    `last_reconcile_at`          datetime              DEFAULT NULL,
    `create_user_id`             int                   DEFAULT NULL,
    `update_user_id`             int                   DEFAULT NULL,
    `deleted`                    tinyint(1)   NOT NULL DEFAULT 0,
    `create_time`                datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`                datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_lake_ods_table_target` (`ods_database_binding_id`, `target_table_name`),
    UNIQUE KEY `uk_lake_ods_table_source` (`ods_database_binding_id`, `source_object_ref_id`),
    KEY `idx_lake_ods_table_status` (`resource_status`, `management_level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='双模入湖 ODS Table Projection';

CREATE TABLE `t_seatunnel_web_lake_job_relation`
(
    `id`                         bigint       NOT NULL COMMENT '主键',
    `ods_database_binding_id`    bigint       NOT NULL,
    `table_mapping_id`           bigint                DEFAULT NULL,
    `relation_scope`             varchar(32)  NOT NULL COMMENT 'TABLE/NAMESPACE',
    `job_runtime_type`           varchar(32)  NOT NULL COMMENT 'BATCH/STREAMING',
    `job_id`                     bigint       NOT NULL COMMENT 'SeaTunnel Job Definition ID',
    `job_version`                int          NOT NULL,
    `relation_status`            varchar(32)  NOT NULL DEFAULT 'ACTIVE',
    `source_endpoint_snapshot`   longtext,
    `sink_endpoint_snapshot`     longtext,
    `schema_save_mode_snapshot`  varchar(64)           DEFAULT NULL,
    `create_time`                datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`                datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_lake_job_relation_binding_job_scope`
        (`ods_database_binding_id`, `job_id`, `relation_scope`),
    KEY `idx_lake_job_relation_table` (`table_mapping_id`, `relation_status`),
    KEY `idx_lake_job_relation_job` (`job_id`, `relation_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='双模入湖任务关系';

CREATE TABLE `t_seatunnel_web_lake_lifecycle_policy`
(
    `id`              bigint       NOT NULL COMMENT '主键',
    `policy_name`     varchar(128) NOT NULL,
    `version`         int          NOT NULL DEFAULT 1,
    `status`          varchar(32)  NOT NULL DEFAULT 'DRAFT',
    `granularity`     varchar(16)  NOT NULL COMMENT 'DAY/MONTH/YEAR',
    `retention_count` int          NOT NULL COMMENT '历史分区保留数',
    `description`     varchar(1024)         DEFAULT NULL,
    `create_user_id`  int                   DEFAULT NULL,
    `update_user_id`  int                   DEFAULT NULL,
    `create_time`     datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`     datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_lake_lifecycle_policy_name` (`policy_name`),
    KEY `idx_lake_lifecycle_policy_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='双模入湖生命周期策略';

CREATE TABLE `t_seatunnel_web_lake_table_lifecycle_binding`
(
    `id`                    bigint       NOT NULL COMMENT '主键',
    `table_mapping_id`      bigint       NOT NULL,
    `policy_id`             bigint                DEFAULT NULL,
    `policy_version`        int                   DEFAULT NULL,
    `partition_column`      varchar(128) NOT NULL,
    `granularity`           varchar(16)  NOT NULL,
    `retention_count`       int                   DEFAULT NULL COMMENT '唯一 desired source',
    `actual_retention_count` int                  DEFAULT NULL,
    `policy_snapshot_json`  longtext,
    `status`                varchar(32)  NOT NULL DEFAULT 'PENDING',
    `operation_token`       varchar(128)          DEFAULT NULL,
    `generation`            int          NOT NULL DEFAULT 1,
    `lock_version`          int          NOT NULL DEFAULT 1,
    `error_code`            varchar(128)          DEFAULT NULL,
    `error_message`         varchar(4096)         DEFAULT NULL,
    `create_user_id`        int                   DEFAULT NULL,
    `update_user_id`        int                   DEFAULT NULL,
    `create_time`           datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`           datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_lake_table_lifecycle_table` (`table_mapping_id`),
    KEY `idx_lake_table_lifecycle_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='双模入湖表生命周期绑定';

CREATE TABLE `t_seatunnel_web_lake_external_catalog_binding`
(
    `id`                    bigint       NOT NULL COMMENT '主键',
    `lake_data_source_id`   bigint       NOT NULL COMMENT 'Doris 湖数据源 ID',
    `source_data_source_id` bigint       NOT NULL COMMENT '外部源数据源 ID',
    `catalog_name`          varchar(128) NOT NULL,
    `adapter`               varchar(32)  NOT NULL COMMENT 'MYSQL/POSTGRESQL/ORACLE',
    `scope`                 varchar(32)  NOT NULL COMMENT 'ALL/DATABASE/TABLE',
    `desired_spec_json`     longtext     NOT NULL COMMENT '脱敏 desired spec',
    `desired_spec_hash`     char(64)     NOT NULL,
    `credential_revision`   varchar(128)          DEFAULT NULL,
    `validation_status`     varchar(32)           DEFAULT NULL,
    `resource_status`       varchar(32)  NOT NULL DEFAULT 'PENDING_CREATE',
    `lock_version`          int          NOT NULL DEFAULT 1,
    `generation`            int          NOT NULL DEFAULT 1,
    `operation_token`       varchar(128)          DEFAULT NULL,
    `error_code`            varchar(128)          DEFAULT NULL,
    `error_message`         varchar(4096)         DEFAULT NULL,
    `last_reconcile_at`     datetime              DEFAULT NULL,
    `create_user_id`        int                   DEFAULT NULL,
    `update_user_id`        int                   DEFAULT NULL,
    `deleted`               tinyint(1)   NOT NULL DEFAULT 0,
    `create_time`            datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`            datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_lake_catalog_source` (`source_data_source_id`),
    UNIQUE KEY `uk_lake_catalog_target` (`lake_data_source_id`, `catalog_name`),
    KEY `idx_lake_catalog_status` (`resource_status`, `validation_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='双模入湖 Doris External Catalog Binding';

CREATE TABLE `t_seatunnel_web_lake_resource_operation`
(
    `id`               bigint       NOT NULL COMMENT '主键',
    `resource_type`    varchar(64)  NOT NULL,
    `resource_id`      bigint       NOT NULL,
    `generation`       int          NOT NULL,
    `operation_type`   varchar(64)  NOT NULL,
    `operation_token`  varchar(128) NOT NULL,
    `request_hash`     char(64)              DEFAULT NULL,
    `status`           varchar(32)  NOT NULL DEFAULT 'PENDING',
    `started_at`       datetime              DEFAULT NULL,
    `finished_at`      datetime              DEFAULT NULL,
    `error_code`       varchar(128)          DEFAULT NULL,
    `error_summary`    varchar(2000)         DEFAULT NULL COMMENT '脱敏摘要，不存连接 JSON/DDL',
    `operator_id`      int                   DEFAULT NULL,
    `create_time`      datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time`      datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_lake_operation_token` (`operation_token`),
    KEY `idx_lake_operation_resource` (`resource_type`, `resource_id`, `generation`, `started_at`),
    KEY `idx_lake_operation_status` (`status`, `started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='双模入湖外部操作意图与结果';
