package org.apache.seatunnel.web.api.lake.query;

/** Stable classifications for structured query validation failures. */
public enum LakeQueryValidationCode {
    REQUEST_REQUIRED("LAKE_QUERY_REQUEST_REQUIRED"),
    TABLE_REQUIRED("LAKE_QUERY_TABLE_REQUIRED"),
    IDENTIFIER_REQUIRED("LAKE_QUERY_IDENTIFIER_REQUIRED"),
    IDENTIFIER_INVALID("LAKE_QUERY_IDENTIFIER_INVALID"),
    COLUMNS_REQUIRED("LAKE_QUERY_COLUMNS_REQUIRED"),
    COLUMN_REQUIRED("LAKE_QUERY_COLUMN_REQUIRED"),
    COLUMN_TABLE_MISMATCH("LAKE_QUERY_COLUMN_TABLE_MISMATCH"),
    COLUMN_UNKNOWN("LAKE_QUERY_COLUMN_UNKNOWN"),
    COLUMN_UNSUPPORTED("LAKE_QUERY_COLUMN_UNSUPPORTED"),
    COLUMN_SENSITIVE("LAKE_QUERY_COLUMN_SENSITIVE"),
    DUPLICATE_COLUMN("LAKE_QUERY_DUPLICATE_COLUMN"),
    DUPLICATE_ALLOWLIST_COLUMN("LAKE_QUERY_DUPLICATE_ALLOWLIST_COLUMN"),
    AMBIGUOUS_OUTPUT_ALIAS("LAKE_QUERY_AMBIGUOUS_OUTPUT_ALIAS"),
    JOIN_REQUIRED("LAKE_QUERY_JOIN_REQUIRED"),
    JOIN_CATALOGS_NOT_DISTINCT("LAKE_QUERY_JOIN_CATALOGS_NOT_DISTINCT"),
    JOIN_TYPE_INVALID("LAKE_QUERY_JOIN_TYPE_INVALID"),
    LIMIT_REQUIRED("LAKE_QUERY_LIMIT_REQUIRED"),
    LIMIT_NOT_POSITIVE("LAKE_QUERY_LIMIT_NOT_POSITIVE"),
    MAX_ROWS_INVALID("LAKE_QUERY_MAX_ROWS_INVALID");

    private final String code;

    LakeQueryValidationCode(String code) {
        this.code = code;
    }

    public String code() {
        return code;
    }
}
