package org.apache.seatunnel.web.core.client.gateway;

import jakarta.annotation.Resource;
import org.apache.seatunnel.web.core.client.port.SeaTunnelClientRuntimeGateway;
import org.apache.seatunnel.web.engine.client.rest.SeaTunnelRestClient;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

/**
 * REST-based implementation of {@link SeaTunnelClientRuntimeGateway}.
 *
 * <p>This gateway delegates SeaTunnel runtime operations to {@link SeaTunnelRestClient},
 * such as querying metrics, job logs, checkpoint overview, and checkpoint history.</p>
 *
 * <p>This class belongs to the engine client adapter layer. The core client module
 * only depends on {@link SeaTunnelClientRuntimeGateway} and does not know the
 * concrete REST implementation details.</p>
 */
@Component
public class SeaTunnelRestClientRuntimeGateway implements SeaTunnelClientRuntimeGateway {

    @Resource
    private SeaTunnelRestClient seaTunnelRestClient;

    /**
     * Queries runtime metrics of the specified SeaTunnel client.
     *
     * @param clientId SeaTunnel client id
     * @return raw runtime metrics returned by SeaTunnel REST API
     */
    @Override
    public List<Map<String, Object>> metrics(Long clientId) {
        return seaTunnelRestClient.systemMonitoringInformation(clientId);
    }

    /**
     * Queries job logs from the SeaTunnel engine.
     *
     * @param clientId SeaTunnel client id
     * @param engineJobId job id generated by the SeaTunnel engine
     * @param format log response format, such as json or text
     * @return engine job log content
     */
    @Override
    public String jobLogs(
            Long clientId,
            String engineJobId,
            String format
    ) {
        return seaTunnelRestClient.jobLogs(clientId, engineJobId, format);
    }

    /**
     * Queries checkpoint overview of a SeaTunnel job.
     *
     * @param clientId SeaTunnel client id
     * @param jobId SeaTunnel engine job id
     * @return checkpoint overview returned by SeaTunnel REST API
     */
    @Override
    public Map<String, Object> checkpointOverview(
            Long clientId,
            Long jobId
    ) {
        return seaTunnelRestClient.checkpointOverview(clientId, jobId);
    }

    /**
     * Queries checkpoint history of a SeaTunnel job.
     *
     * @param clientId SeaTunnel client id
     * @param jobId SeaTunnel engine job id
     * @param pipelineId optional pipeline id
     * @param limit max history size
     * @param status optional checkpoint status filter
     * @return checkpoint history returned by SeaTunnel REST API
     */
    @Override
    public List<Map<String, Object>> checkpointHistory(
            Long clientId,
            Long jobId,
            Long pipelineId,
            Integer limit,
            String status
    ) {
        return seaTunnelRestClient.checkpointHistory(
                clientId,
                jobId,
                pipelineId,
                limit,
                status
        );
    }
}
